version: "2" 
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
    config:
      threshold: "A"
ratings:
  paths:
  - "**.py"

exclude_patterns:
- "**/migrations/"
- "**/tests/"
- "**/*.js"
